import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Home from './Home';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>InternGo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/aiml.jpeg" />
      </Head>
      <main className={styles.main}>
        <Home />
      </main>
    </>
  );
}
